name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 18 * * *"  # runs every day at 6 PM UTC
  workflow_dispatch:        # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph

    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: tamannadeshwal

      - name: Commit & Push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A .
          git commit -m "Generate 3D contribution graph" || exit 0
          git push
