name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: tamannadeshwal
          SETTING_JSON: '{"fileName":"profile-3d-contrib/profile-night-rainbow.svg","otherSettings":{}}'

      - name: Commit & Push
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A .
          git diff --cached --quiet || git commit -m "Update 3D contribution graph"
          git push
